### PR TITLE
Add support for passing inline vars to GOSS

### PR DESCRIPTION
**Pull request by EleanorRigby**
- Adds UI logs
- Adds inspect mode to allow disabling packer failure on goss test failure.

### CODE REVIEW

**Comment by EleanorRigby** [comment]
cc: @codenrhoden

**Comment by EleanorRigby** [comment]
Output for the run
```
goss version v0.3.13
==> amazon-2: Uploading goss tests...
    amazon-2: Creating directory: /tmp/goss
    amazon-2: Inline variables are map[hello:world]
    amazon-2: Inline variable string is --vars-inline {"hello":"world"}
    amazon-2: Uploading Dir packer/goss
    amazon-2: Creating directory: /tmp/goss/goss
==> amazon-2:
==> amazon-2:
==> amazon-2:
==> amazon-2: Running goss tests...
    amazon-2: Command : cd /tmp/goss && sudo /tmp/goss-0.3.13-linux-amd64 --gossfile goss/goss.yaml  --vars-inline {"hello":"world"} validate --retry-timeout 0s --sleep 1s -f json -o pretty
==> amazon-2: Goss tests ran successfully
```

**Comment by EleanorRigby** [comment]
@fishnix : The PR is ready for merge. I have finished adding all features. I am able to use it with packer to build & **verify** an Amazon ami.

##### Test Results (`Inline Vars` and `Command Print`
```
==> amazon-2: Running goss tests...
    amazon-2: Command : cd /tmp/goss && sudo /tmp/goss-0.3.13-linux-amd64 --gossfile goss/goss.yaml --vars /tmp/goss/goss-vars.yaml --vars-inline '{"containerd_version":"1.3.4","kubernetes_cni_source_type":"http","kubernetes_cni_version":"0.8.6","kubernetes_source_type":"http","kubernetes_version":"1.16.11"}' validate --retry-timeout 0s --sleep 1s -f json -o pretty
    amazon-2: {
    amazon-2:     "results": [
```

##### Test Results (`Inspect` mode)
```
    amazon-2:         }
    amazon-2:     ],
    amazon-2:     "summary": {
    amazon-2:         "failed-count": 1,
    amazon-2:         "summary-line": "Count: 16, Failed: 1, Duration: 0.193s",
    amazon-2:         "test-count": 16,
    amazon-2:         "total-duration": 193441345
    amazon-2:     }
    amazon-2: }
==> amazon-2: Goss tests failed
==> amazon-2: Inpect mode on : proceeding without failing Packer
==> amazon-2: Stopping the source instance...
    amazon-2: Stopping instance
==> amazon-2: Waiting for the instance to stop...
==> amazon-2: Creating AMI capa-ami-amazon-2-1.16.11-01-1595487373 from instance i-0d90e266727c977a0
    amazon-2: AMI: ami-0c8fee61e2bc00f4c
==> amazon-2: Waiting for AMI to become ready...
==> amazon-2: Copying/Encrypting AMI (ami-0c8fee61e2bc00f4c) to other regions...
```

**Comment by fishnix** [comment]
Looks good, thanks! 👍

**Pull request merged**
