### PR TITLE
Url ssl support, auth support and custom gossfile support

### PR DESCRIPTION
**Pull request by vamegh**

### CODE REVIEW

**Comment by fishnix** [comment]
Hi! Thanks for the PR!  It looks good.  I'll test it a bit and merge it in afterwards.

**Comment by vamegh** [comment]
Hi @fishnix please hold off Im trying to add some further stuff - testing and I  cleaned it up some.

**Comment by vamegh** [comment]
Hi @fishnix I have now tested everything here - its all working, if your happy to merge it in I would be happy. 

Stuff added:

Custom Gossfile suport (the --gossfile flag)
tests now supports uploading directories (I just linked to your existing function and perma set ignore to be blank - I dont think this will ever be needed)
Username and Password for auth to download goss from custom internal services. 
Ssl Cert Check (can disable cert checking if required - for custom internal services using self-signed certs)

I think that about covers everything - we have tested here locally and it seems to be working as expected.

**Comment by vamegh** [comment]
Im closing this - as this was quite messy

**Pull request closed without merging**
