### PR TITLE
suport new Packer plugin installation

### PR DESCRIPTION
**Pull request by FalcoSuessgott**
This PR is based #59 and adds support for the new `packer init`plugin installation.

I updated the README.md accordingly.

You can test it with my fork:

```hcl
# packer.pkr.hcl
packer {
  required_version = ">= 1.9.0"

  required_plugins {
    goss = {
      version = "0.0.7"
      source  = "github.com/FalcoSuessgott/goss"
    }
  }
}
```

```bash
$> PACKER_PLUGIN_PATH=_packer-plugins packer init .
Installed plugin github.com/falcosuessgott/goss v0.0.7 in "_packer-plugins/github.com/falcosuessgott/goss/packer-plugin-goss_v0.0.7_x5.0_linux_amd64"
$> tree _packer-plugins 
_packer-plugins
└── github.com
    └── falcosuessgott
        └── goss
            ├── packer-plugin-goss_v0.0.7_x5.0_linux_amd64
            └── packer-plugin-goss_v0.0.7_x5.0_linux_amd64_SHA256SUM
```

### CODE REVIEW

**Comment by MadJlzz** [comment]
I tried on my end with the solution of @FalcoSuessgott and I can confirm it works well 🎆

**Comment by micxer** [comment]
Any chance this gets merged soon? This really helps a lot!

**Review by btassone — COMMENTED** [review]
👍

**Comment by FalcoSuessgott** [comment]
Thanks for  merging! In order to make it available, you would have to tag it. In the README I assumed the next tag would be 3.2.0 :)

**Comment by btassone** [comment]
> Thanks for merging! In order to make it available, you would have to tag it. In the README I assumed the next tag would be 3.2.0 :)

doing this on an ipad while watching Baki so im a touch slow atm 😂. i’ll adjust the tag

**Comment by btassone** [comment]
> Thanks for merging! In order to make it available, you would have to tag it. In the README I assumed the next tag would be 3.2.0 :)

is the other PR from 2021 still relevant btw? @FalcoSuessgott

**Comment by FalcoSuessgott** [comment]
Hehe no problem mate. AFAIK the other PR aswell as some issues can be closed now. I will comment the issues. :)

**Comment by btassone** [comment]
> Hehe no problem mate. AFAIK the other PR aswell as some issues can be closed now. I will comment the issues. :)

Roger that! I’ll start cleaning up the ones u comment on. Appreciate it!

**Comment by F21** [comment]
Hey @FalcoSuessgott and @btassone, thanks so much for getting this in. Can the repository be renamed to `packer-plugin-goss` to support plugin installation?

Packer expects plugin repositories to have the following pattern: `github.com/org/packer-plugin-xxxx`

Currently, `packer init` failes because the repository is named `YaleUniversity/packer-provisioner-goss`:
```
Failed getting the "github.com/yaleuniversity/goss" plugin:
1 error occurred:
        * GET https://api.github.com/repos/yaleuniversity/packer-plugin-goss/git/matching-refs/tags: 404 Not Found []
```

**Comment by FalcoSuessgott** [comment]
Oh, yeah indeed. I forgot that I renamed my fork to `packer-plugin-goss` in order to make it work.

@btassone do you have the permissions to rename the repo?

**Comment by btassone** [comment]
Yep! I'll make that change here shortly. Thanks for the heads up.

**Comment by F21** [comment]
ping @btassone

**Comment by ian-flores** [comment]
Hi folks, we would also benefit from this renaming so if there is anyway we (or I personally) can help land this please post here so we can do so.

**Comment by btassone** [comment]
@ian-flores @F21  @FalcoSuessgott 

Opened up a new pr https://github.com/YaleUniversity/packer-plugin-goss/pull/70 to continue discussion on this

**Comment by btassone** [comment]
Just as an update in case folks didn't see in the other PR. You should be all set.

**Pull request merged**
